pipeline:
  name: gcp-iacm-terraform-vm-import
  identifier: gcpiacmterraformvmimport
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: infra
        identifier: infra
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: reethu
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 10m
                  spec:
                    command: apply
              - step:
                  type: IACMTerraformPlugin
                  name: import
                  identifier: import
                  spec:
                    command: import
                    delegateSelectors:
                      - kubernetes-delegate-reethu
                  timeout: 10m
        tags: {}
