pipeline:
  name: gcp-iacm-terraform-vm-import
  identifier: gcpiacmterraformvmimport
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: infra
        identifier: infra
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: reethu
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: Init
                  identifier: Init
                  spec:
                    command: init
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: import
                  identifier: import
                  spec:
                    command: import
                    delegateSelectors:
                      - kubernetes-delegate-reethu
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: Plan
                  identifier: Plan
                  spec:
                    command: plan
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: APply
                  identifier: APply
                  spec:
                    command: apply
                  timeout: 1h
              - step:
                  type: IACMTerraformPlugin
                  name: Destroy
                  identifier: Destroy
                  spec:
                    command: destroy
                  timeout: 1h
        tags: {}
